### ISSUE TITLE
Symbol is not defined exception when invoking "autoTableHtmlToJson" - IE 10 and IE 11

### ISSUE THREAD

**Issue by Davide82x** [simonbengtsson/jsPDF-AutoTable#143]
Hi! 

I'm facing the issue in the subject while testing the plugin using IE 10 and IE 11. When I invoke the function "autoTableHtmlToJson", the function fails saying that "Symbol is not defined". It works perfectly in other browsers (Chrome, Firefox, Opera, Safari, ...). 

The exception is raised at line 397 (jspdf.plugin.autotable.src.js). 

Has anyone experienced this issue?

Any idea? 

Thanks

**Comment by Davide82x** [comment]
I found that Symbol.iterator is not supported by IE (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/iterator). 

So I replaced the Symbol.iterator with a "for loop" statement in the "jsPDF.API.autoTableHtmlToJson" function and it works also in IE (10 and 11). 

```
// FOR loop statement
for(var it=0; it < Object.keys(columns).length; it++) {
var j = Object.keys(columns)[it];

var cell = tableRow.cells[j];
var val = cell ? cell.textContent.trim() : '';
rowData.push(val);
}
_iteratorNormalCompletion = true
```

and I commented this code

```
//    for (var _iterator = Object.keys(columns)[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
//        var j = _step.value;
//      var cell = tableRow.cells[j];
//      var val = cell ? cell.textContent.trim() : '';
//      rowData.push(val);
//  }
```

**Comment by simonbengtsson** [comment]
Oops, turns out I forgot to include the babel polyfills. Will release a new version in a moment.

**Comment by simonbengtsson** [comment]
Hmm, I think it's solved now. At least I don't get the issue anymore. Can you verify?

**Comment by razorrazor** [comment]
Hi! The problem still continues with version 2.0.28. Is it necessary to include the polyfill.js after the autotable.min.js?

**Comment by simonbengtsson** [comment]
My bad, added proper polyfills in `2.0.29` now. Thanks for letting me know!

I did not want to add the entire `babel-polyfills` however since it's huge. In the unlikely scenario that other IE issues appear now or in the future simple write here or submit a new issue and I'll look into it.
